name: Maria Victoria Photography
favicon: null
layout_spectrum: 0.13247959199361503
typography_spectrum: 0.6042848012875766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.17896587937138975
  lightness: 0.7263106454629451
  saturation: 0.29413040494546294
  rhythmicContrast: 0.33519480703398585
purpose: []
