name: Maria Victoria
favicon: null
layout_spectrum: 0.48701
typography_spectrum: 1
title: Fine Art Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef3f6'
    - '#c7c2c6'
    - '#000000'
    - '#515151'
    - '#7a8773'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
